import type { Rules } from '../types'

declare const data: Rules<
  | 'json/array-bracket-newline'
  | 'json/array-bracket-spacing'
  | 'json/array-element-newline'
  | 'json/comma-dangle'
  | 'json/comma-style'
  | 'json/indent'
  | 'json/key-spacing'
  | 'json/no-bigint-literals'
  | 'json/no-binary-expression'
  | 'json/no-binary-numeric-literals'
  | 'json/no-comments'
  | 'json/no-dupe-keys'
  | 'json/no-escape-sequence-in-identifier'
  | 'json/no-floating-decimal'
  | 'json/no-hexadecimal-numeric-literals'
  | 'json/no-infinity'
  | 'json/no-multi-str'
  | 'json/no-nan'
  | 'json/no-number-props'
  | 'json/no-numeric-separators'
  | 'json/no-octal-numeric-literals'
  | 'json/no-octal'
  | 'json/no-parenthesized'
  | 'json/no-plus-sign'
  | 'json/no-regexp-literals'
  | 'json/no-sparse-arrays'
  | 'json/no-template-literals'
  | 'json/no-undefined-value'
  | 'json/no-unicode-codepoint-escapes'
  | 'json/no-useless-escape'
  | 'json/object-curly-newline'
  | 'json/object-curly-spacing'
  | 'json/object-property-newline'
  | 'json/quote-props'
  | 'json/quotes'
  | 'json/sort-keys'
  | 'json/space-unary-ops'
  | 'json/valid-json-number'
  | 'json/vue-custom-block/no-parsing-error'
  | 'no-unused-expressions'
  | 'no-unused-vars'
  | 'strict'
>
export default data
