language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - bc
before_install:
- npm install -g npm
script:
- gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq $JQ_BINARY && chmod +x ~/bin/jq
- jq -r '.peerDependencies | to_entries[] | "\"\(.key)@\(.value)\""' package.json
  | xargs npm i
- "./manage ci"
env:
  global:
  - JQ_BINARY="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
  - PATH="/usr/bin:$PATH"
  - secure: AkuHO7qQ2NTk5D59Z7oRS6XIDIaWDLDTCLEo5x1GMdxJHaoTjva8unuP/zXq4YbEwal1banJ8/+x6cARyzesYAz2aZ6Nuygq7yPHL/KyyPs2dr7Ke+klEg6NAJNZtIgVz1txy0kFioxA846G784Xpovw8TCLngJskJmKId9liGONNhBmttvBD1ayWPRhjgVwKvP2uToLKD1lFvKU2RMq3rD12F/O+I34gtLw3uFDR+9NmqZ5ZBQN6fWoNiZHTMnlpET5MwlFuA79p0eoB/6UlhbmfO2pY0kZKhbzBVaKcGjW9E8KrTpySwWNIJhWsCDdarBAbWTYBI805EX7xk1iKayAzHywr1v+s40F4EI0/x667gFvbdkJxKSlPOzbx/lUzsr2ffXAGgMSSlabzWzxVvNq7HUNP8y/tPB3IX3QQ1XsILuHMU1v/EWLhIeE12VBUkXY8SiaURg5+A7n7Hmd7WIvBLs4S5qdN/3ZxJRq3Uo94pZ/ZVY2fudou11PuhHNhZ7Iy1fU/G+sr6OTf56chCZB238Pyw8RDW+AFlA/AIMqe0ULaA1o4+V3g61IDiHPem+cnaPlYEkSaA4kdz/xqrYq7qF4BtIWrPicOQo9C4ctjqltC2BQYLRg3WMGq0Qbn8qjofISAUciAfkOlVAcozNdogjVZjKON6mSV3XF3kU=
