dist: xenial
language: node_js
before_install:
- npm install -g npm
script:
- jq -r '.peerDependencies | to_entries[] | "\"\(.key)@\(.value)\""' package.json
  | xargs npm install --no-save
- npm run test
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: fmDcyXHYLerdCmBShPs2CzoTbugFWOz+2c4j6VNS45wUfE/jwHMIwtHwtsjrHc4FxNdlDiM3GfXJCctt2p7hy3LXqMo2FUdBKbPqWEQmGwCgGIm+xy2+lHP6BEEuF9P/ABwIla+Ofwi6TI/Mz03rqJgif7SWaioPyG3PTmI3NJ676/cXHTXk3ykSc1x3uFrLvPu+0FpRAD+rOa9oroo/Nb3E21iujGNGRiunVEZCU5T+2Cf4796a8jYIPGsRDxUvXq7FLhSQ3lg8KG9iywFZ74TwHhFM7fXSoeKSrUwbf9KVPVWrtPY20LPKQdJFC+WX8K759KGy5UUG7kYu7JbyLtYP7s5x62R1EPr++71VK821VY0HEno+EjzCLxKlcjEGEc6WhNL07+JDN0oPk3qjglYEFVB/DPHsAZ+nZmmyaqAc3NBzQNzIT1yJvltLH7P2xeSz5kqjrPK2E7BM+6q8zMpUXTNHHExEy2YedqcOt6pFwve7HutVPlztWCtrO18VxQ3xSi2G7PP5Dtu/4Wf8c+/pSpHHNtCDU/I0Lch3n66b2rhn8HPlTJLUA4C+5zihtISYvKEpll2r0+LFfDVf91lka/YGoJoHAfjQKcHPiR2GgnB1ZhM4DKWHizgcDxB8mRhNL0pkXgWnNa+93YZDb9RK3TkF6wX0ZEZE4l0Vx48=
  - secure: awS846dLWW5VckGCkQY5o8NPPQy7il0QHfOZ9NK6zHQjrdP7YPJzVjTgnrtr/rZotUsIsVLuIAhUmC/BFyLQEYUh27ZVsFTW0ZCauNcOf+uefoyCUgp9j6uW0dc8awCfwGDoCt+LnCNVPiTmcbyOSF+iPveluXj+K+Ls7IhVbU4crN+fzt4fnqreuD+1ydNcMVEeDWLiNczlQ9ePVJKG0i8G5KXKw0TOqQrcMRHLp1b8+ruPIt5KmvgUZR0S7t+ISN4l+QwMnPIqndZ7IIBQgZ4uHH21KUd9+wv5mQBsz2r+oIoirL1anOiGYzZI/pFh1FHCqzRNOs8Sl90WE4+cgHYMDQ0yCCHB9ODXWt4Zt73zZhXD5J7rrICp4oPjZz2T+k7ZT3QnojnsveDoAf2QKlNirdppQ+nAiLSalaLmkyNE9g2/HkXxPJOwfO3G+iRH9xnPVWoLvfQWGgCURIcsbrR9b9HPLqm+snvBI6D4qyF5rKfl1GhV7fAccjzr3dWwxs7w2o0/xzYqVXNkzElZErPAazS37rBpxW4dhCIGEwEXvvLG99S45RQi8G9tolYVTlMSVdlO1m5ZXUM3Wu4RSxFTPlTxyXAPqjn456qhyLljDsnQkTy7KYtjqG/sV4kd8N7eL13B4rwNmPzvVerB8W73LWLsbb78wbBp7QeGLFs=
