// Names whose import-as-local-binding would shadow a JavaScript global.
// Kept narrowly to widely-shipped ES globals; DOM/Node names are opt-in via
// `additionalGlobals`.
export const jsGlobals: ReadonlySet<string> = new Set([
  'Array',
  'BigInt',
  'Boolean',
  'Date',
  'Error',
  'EvalError',
  'Function',
  'globalThis',
  'Infinity',
  'JSON',
  'Map',
  'Math',
  'NaN',
  'Number',
  'Object',
  'Promise',
  'Proxy',
  'RangeError',
  'Reflect',
  'RegExp',
  'Set',
  'String',
  'Symbol',
  'SyntaxError',
  'TypeError',
  'undefined',
  'URIError',
  'WeakMap',
  'WeakSet',
])
