#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx syncpack set-semver-ranges \
  --semver-range "^" \
  --peer \
  --source 'package.json' || exit 1

npx syncpack set-semver-ranges \
  --dev \
  --source 'package.json' || exit 1

npx syncpack format \
  --source 'package.json' || exit 1

npm install || exit 1

git add package.json package-lock.json

npm run test
