name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
permissions:
  contents: read
  packages: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    uses: ./.github/workflows/workflow-call-context.yaml

  ci:
    needs:
      - context
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: ./.github/workflows/workflow-call-ci.yaml
    with:
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
