name: release
on:
  schedule:
    - cron: '10 16 * * 2'
  repository_dispatch:
    types: [release]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.5
      - name: setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: install dependencies
        run: |
          npm install
          jq -r '.peerDependencies | to_entries[] | "\"\(.key)@\(.value)\""' package.json | xargs npm install --no-save
      - name: test
        run: npm run test
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
