name: release
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.4.0
      - name: setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: test
        run: pnpm run test
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
