name: Test
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          version: 13
      - name: Install dependencies
        run: |
          npm install
          jq -r '.peerDependencies | to_entries[] | "\"\(.key)@\(.value)\""' package.json | xargs npm install --no-save
      - name: Test
        run: npm run test
