name: test
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - name: install dependencies
        run: |
          npm install
          jq -r '.peerDependencies | to_entries[] | "\"\(.key)@\(.value)\""' package.json | xargs npm install --no-save
      - name: test
        run: npm run test
