on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string
      ref:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:

permissions:
  contents: read
  packages: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      # - name: write .npmrc
      #   run: |
      #     cat << EOF > "$HOME/.npmrc"
      #       //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
      #       @escapace:registry=https://npm.pkg.github.com
      #       always-auth=true
      #     EOF
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          run_install: false
          version: ${{ inputs.pnpm-version }}
      - id: pnpm-store-path
        name: get pnpm store directory
        run: echo "value=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: pnpm cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ steps.pnpm-store-path.outputs.value }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store
      - name: install dependencies
        run: pnpm install
      - name: typecheck
        run: pnpm run typecheck
      - name: build
        run: pnpm run build
      - name: test
        run: pnpm run test
      - name: code coverage
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - if: inputs.version != ''
        name: pnpm pack
        run: |
          echo "$(jq '.version="${{ inputs.version }}"' package.json)" > package.json
          pnpm pack
      - if: inputs.version != ''
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: '*.tgz'
          retention-days: 3
